[workspace]
members = ["wasm"]
default-members = ["wasm"]
resolver = "2"

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[profile.dev.package."*"]
opt-level = 3
debug = false
