name: Bump
on:
  workflow_dispatch:
    inputs:
      strategy:
        description: The strategy to bump the version number.
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Enable corepack
        run: corepack enable
      - name: Bump
        uses: hexium310/workflows/.github/actions/bump@master
        with:
          strategy: ${{ github.event.inputs.strategy }}
          package-ecosystems: '["cargo", "yarn"]'
          token: ${{ secrets.BUMP_TOKEN }}
